### ISSUE TITLE
AndroidManifest.xml not found

### ISSUE THREAD

**Issue by GeneCaoHQ** [idamobile/android-toolbox-plugin#1]
AndroidManifest.xml not found,but my project have one.
![image](https://cloud.githubusercontent.com/assets/5389159/2980394/33a5a6de-dbea-11e3-9e8b-5d44295fda34.png)

**Comment by dolwin** [comment]
I these two days have also met this question.
How did you solve the problem?

**Comment by MercurieVV** [comment]
+1

**Comment by thalespf** [comment]
+1

**Comment by westito** [comment]
+1

**Comment by focuslau** [comment]
+1

**Comment by shaubert** [comment]
Sorry guys, I'll fix it on this week.

**Comment by shaubert** [comment]
Plug-in has been submitted for moderation, and will be processed within two working days.
