### ISSUE TITLE
Why not put updates into the place you took the code from ?

### ISSUE THREAD

**Issue by Yinten** [idamobile/android-toolbox-plugin#2]
We could make a big tool for everyone was what I was going for 5 years ago... but everyone keeps jacking the different pieces of code and rereleasing ti.     This community has turned into trash after employers starting thinking people with GitHubs  and projects were original.

**Comment by Yinten** [comment]
Blatant rip off

**Comment by shaubert** [comment]
Hi, angry man. What project you are talking about?

**Comment by Yinten** [comment]
Think this is incorrect, it seems like you wrote it.
