### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by michalciolek** [idamobile/android-toolbox-plugin#3]
With Android Studo 1.2. beta 3 after pick package I get:

NoSuchMethodError com.intellij.ide.projectView.impl.nodes.PackageUtil.getDirectories(Lcom/intellij/psi/PsiPackage;Lcom/intellij/openapi/project/Project;Lcom/intellij/openapi/module/Module;Z)[Lcom/intellij/psi/PsiDirectory;

**Comment by shaubert** [comment]
Fixed in 1.1.4. Plug-in has been submitted for moderation, and will be processed within two working days.
